//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Site</summary>
	[PublishedContentModel("site")]
	public partial class Site : PublishedContentModel, ILayout
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "site";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Site(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Site, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Area code: ISO 3166-1 alpha-2.  Sverige = SE
		///</summary>
		[ImplementPropertyType("areaCode")]
		public string AreaCode
		{
			get { return this.GetPropertyValue<string>("areaCode"); }
		}

		///<summary>
		/// Background Image
		///</summary>
		[ImplementPropertyType("backgroundImage")]
		public IPublishedContent BackgroundImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("backgroundImage"); }
		}

		///<summary>
		/// Cookie warning
		///</summary>
		[ImplementPropertyType("cookieWarning")]
		public IHtmlString CookieWarning
		{
			get { return this.GetPropertyValue<IHtmlString>("cookieWarning"); }
		}

		///<summary>
		/// Footer
		///</summary>
		[ImplementPropertyType("footer")]
		public Skybrud.Umbraco.GridData.GridDataModel Footer
		{
			get { return this.GetPropertyValue<Skybrud.Umbraco.GridData.GridDataModel>("footer"); }
		}

		///<summary>
		/// Links to Social Media: Specify links to your Company's Social Media
		///</summary>
		[ImplementPropertyType("linksToSocialMedia")]
		public string LinksToSocialMedia
		{
			get { return this.GetPropertyValue<string>("linksToSocialMedia"); }
		}

		///<summary>
		/// Logotype
		///</summary>
		[ImplementPropertyType("logotype")]
		public IPublishedContent Logotype
		{
			get { return this.GetPropertyValue<IPublishedContent>("logotype"); }
		}

		///<summary>
		/// Org name
		///</summary>
		[ImplementPropertyType("orgName")]
		public string OrgName
		{
			get { return this.GetPropertyValue<string>("orgName"); }
		}

		///<summary>
		/// Script on all pages
		///</summary>
		[ImplementPropertyType("scriptOnAllPages")]
		public string ScriptOnAllPages
		{
			get { return this.GetPropertyValue<string>("scriptOnAllPages"); }
		}

		///<summary>
		/// Short description of the organization: Example: Camelonta is a digital agency with a vaste engagement. We build and optimize web applications that are easy and
		///</summary>
		[ImplementPropertyType("shortDescriptionOfTheOrganization")]
		public string ShortDescriptionOfTheOrganization
		{
			get { return this.GetPropertyValue<string>("shortDescriptionOfTheOrganization"); }
		}

		///<summary>
		/// Street address
		///</summary>
		[ImplementPropertyType("streetAddress")]
		public string StreetAddress
		{
			get { return this.GetPropertyValue<string>("streetAddress"); }
		}

		///<summary>
		/// Telephone number
		///</summary>
		[ImplementPropertyType("telephoneNumber")]
		public string TelephoneNumber
		{
			get { return this.GetPropertyValue<string>("telephoneNumber"); }
		}

		///<summary>
		/// Top links
		///</summary>
		[ImplementPropertyType("topLinks")]
		public IEnumerable<IPublishedContent> TopLinks
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("topLinks"); }
		}

		///<summary>
		/// umbracoInternalRedirectId
		///</summary>
		[ImplementPropertyType("umbracoInternalRedirectId")]
		public IPublishedContent UmbracoInternalRedirectId
		{
			get { return this.GetPropertyValue<IPublishedContent>("umbracoInternalRedirectId"); }
		}

		///<summary>
		/// Zipcode
		///</summary>
		[ImplementPropertyType("zipcode")]
		public string Zipcode
		{
			get { return this.GetPropertyValue<string>("zipcode"); }
		}
	}
}
